version: 2

before:
  hooks:
    - go mod tidy
    - go generate

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

nfpms:
  # note that this is an array of nfpm configs
  - #
    vendor: eduhds

    homepage: https://github.com/eduhds/gspm

    maintainer: eduhds <27dhiouz9@mozmail.com>

    description: |-
      GSPM
      Git Services Package Manager.

    license: GPL-3.0

    # Formats to be generated.
    formats:
      - apk
      - deb
      - rpm
      - archlinux
      # - termux.deb
